# Generated by Django 5.2 on 2025-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('delivering_value', 'Delivering Value'), ('easy_to_release', 'Easy to Release'), ('fun', 'Fun'), ('learning', 'Learning'), ('mission', 'Mission'), ('pawns_or_players', 'Pawns or Players'), ('suitable_process', 'Suitable Process'), ('support', 'Support'), ('team_work', 'Team Work'), ('health_of_codebase', 'Health of Codebase')], max_length=50)),
                ('trend', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Green', 'Green')], max_length=10)),
                ('state', models.CharField(choices=[('worse', 'Worse'), ('stable', 'Stable'), ('improving', 'Improving')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
