# Generated by Django 5.2 on 2025-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_vote_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='team',
            field=models.CharField(default='Unkown', max_length=20),
            preserve_default=False,
        ),
    ]
