# Generated by Django 5.2 on 2025-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_vote_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='trend',
            field=models.CharField(max_length=20),
        ),
    ]
