# Generated by Django 5.0.6 on 2025-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0004_item_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teamleader', 'Team Leader'), ('engineer', 'Engineer'), ('admin', 'Admin'), ('department_leader', 'Department Leader'), ('seniormanager', 'Senior Manager')], max_length=20),
        ),
    ]
